name: nav
description: Provide easy way to navigate. Includes lots of routers. You can use this library on Android & iOS.
version: 1.4.2
homepage: https://github.com/bansooknam/nav
#dart format .

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
<<<<<<< HEAD
=======
  build_runner: ^2.3.3
  mockito: ^5.4.4
>>>>>>> 3fd2496 (add mock controller to test pushForResult, popWithResult)

flutter: